blueprint:
  name: "Moz Exp Vol with Conditions"
  description: "Automation for controlling volume with added conditions."
  domain: automation
  input:
    media_player:
      name: Media Player
      selector:
        entity:
          domain: media_player
    volume_level:
      name: Volume Level
      description: "The volume level to set"
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.05
    conditions:
      name: Conditions
      description: "Optional conditions that must be met for the automation to run."
      default: []
      selector:
        condition: {}

mode: restart

trigger:
  platform: state
  entity_id: !input media_player
  attribute: volume_level

condition: !input conditions

action:
  - service: media_player.volume_set
    target:
      entity_id: !input media_player
    data:
      volume_level: !input volume_level
